# Generated by Django 4.2.3 on 2023-07-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='adopt_count',
            field=models.IntegerField(default=0),
        ),
    ]
