# Generated by Django 4.2.3 on 2023-08-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='numChat',
            field=models.IntegerField(default=0),
        ),
    ]
