# Generated by Django 4.2.3 on 2023-08-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_numchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='declare',
            field=models.IntegerField(default=0),
        ),
    ]
